<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accountId</name>
   <tag></tag>
   <elementGuidId>fe3102be-cbf2-4230-a1bf-fa86ac638dd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1c4a45c-66ae-436d-bc7c-390af8134501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db4ba56d-02c7-48fc-8263-f80dd583d4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custId</value>
      <webElementGuid>799da0c0-6a0d-44fb-a345-94679f2f891e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custId</value>
      <webElementGuid>e0c73adc-e775-45fa-a5b3-2e501485b263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6d557305-ef7e-4382-abc8-e1698a6739b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full_width</value>
      <webElementGuid>3e3d5e54-3c24-4c8c-8e4f-37c565052b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custId&quot;)</value>
      <webElementGuid>b1ea1ba3-9a53-4adc-b87d-13894656b710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custId']</value>
      <webElementGuid>d1d8f3ec-92d9-416e-bbd2-fd376a61b264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div/p/input</value>
      <webElementGuid>957db936-22e5-4089-88ad-e9aa8ad70669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>d6c02874-fb56-4d57-bd35-62b38dc75b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'custId' and @id = 'custId']</value>
      <webElementGuid>09eff0d7-7434-41b3-a4b2-d9eb3b36d789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
