<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accountPassword</name>
   <tag></tag>
   <elementGuidId>1a5ffd21-986b-4c55-865d-d80f6fc7ccda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custPw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custPw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2967d752-016a-4cdb-9213-3f28b5fcea38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>07e687a7-9889-4ea1-ad85-c050c32f370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custPw</value>
      <webElementGuid>48eec482-1989-4fe8-b71b-8209a1070f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custPw</value>
      <webElementGuid>0abbff80-5983-4fd7-ac03-fe3802c5aa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>21eb5114-365c-4197-b29d-66cd785b9997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full_width</value>
      <webElementGuid>418f0cf6-1ec7-4db6-9f90-ee746ddf0e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custPw&quot;)</value>
      <webElementGuid>e56ff1b8-9d79-4530-96dc-023900beab81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custPw']</value>
      <webElementGuid>7485af40-3e87-4b9d-bdfe-e840e0131acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div/p[2]/input</value>
      <webElementGuid>94acdb53-94b0-4849-8f7f-959bd9465b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>ce2339be-912a-4237-a56b-eeaf6fd263fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'custPw' and @id = 'custPw']</value>
      <webElementGuid>dc6a3186-288d-4205-a52d-8a69e7aac875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
