<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>element_searchKeyword</name>
   <tag></tag>
   <elementGuidId>a5abe223-a1c4-49b8-9c9a-dad067e456ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='container']/div/div/div/span/span/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>45c251d4-e04a-48de-a322-1af21c50d9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‘클리어런스’</value>
      <webElementGuid>8b7c0936-9e5e-4aa4-820e-76b30250ab9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;sc-11j4cof-0 eNaNsd&quot;]/div[@class=&quot;sc-1nsjl0c-0 eywAbX search-result-title box search-result-title&quot;]/span[@class=&quot;sc-tdjdw3-0 eyJzoR text&quot;]/span[@class=&quot;sc-tdjdw3-0 bPPYGi text&quot;]/strong[1]</value>
      <webElementGuid>2d7e8695-0ed2-4c97-a71b-8bd3ff87313b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='container']/div/div/div/span/span/strong</value>
      <webElementGuid>a285eea0-895d-4ef9-b228-bfe80603a879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORY'])[1]/following::strong[1]</value>
      <webElementGuid>c5c8126d-3125-437b-8c99-dba18a48e792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='상품'])[1]/preceding::strong[1]</value>
      <webElementGuid>e94274bc-b358-494a-958b-ee473cccbfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이벤트'])[1]/preceding::strong[1]</value>
      <webElementGuid>3c8971e0-0368-49b7-8871-1d6482cca4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='‘']/parent::*</value>
      <webElementGuid>76efbd6f-7f3e-4a29-9d24-b0e7a7b3d810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>03cd4e17-ceed-4f43-a574-a5ee31c46684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '‘클리어런스’' or . = '‘클리어런스’')]</value>
      <webElementGuid>88a7917d-40d8-43ec-be06-efd245432624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
